name: Peer Analysis
on: # [push]
# on:
#   # https://crontab.guru ““At 22:00 on every day-of-week from Sunday through Thursday.”
#   schedule:
#     - cron: "0 22 * * 0-4"
  workflow_dispatch: # For being able to manually click 'Run Workflow' button on Github Actions
jobs:
  ASX-Data-Loader:
    runs-on: ubuntu-latest # Look for a lighter image?
    env: 
      CI_COMMIT: Github Actions CI
      GITHUB_ACTIONS_ROOT_DIR: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Specify node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' 
      - name: Install packages
        run: |
          # Similar to npm install, except it's meant to be used in automated environments to make sure a clean install of your dependencies.
          # npm ERR! The `npm ci` command can only install with an existing package-lock.json or
          # npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
          # npm ERR! later to generate a package-lock.json file, then try again.
          npm ci
      # - name: Copy all non-TS files in 'src' folder to 'dist' folder
      #   run: npm run prevscodedebug
      # - name: Transpile to js files
      #   run: |
      #     npm run vscodedebug
      # - name: Create ASX data files 
      #   run: |
      #     node ./dist/scripts/asx.js
      # - name: Commit to the repo
      #   run: |
      #     git config --global user.name "${{ env.CI_COMMIT }}"
      #     git config --global user.email "username@users.noreply.github.com"
      #     git add .
      #     git commit -a -m "${{ env.CI_COMMIT }}" --allow-empty
      #     git push
      - name: Output default
        run: |
          timedatectl
      - name: Setup timezone
          uses: zcong1993/setup-timezone@master
          with:
            timezone: Australia/Sydney
      - name: Output default
        run: |
          timedatectl
