name: Peer Analysis
on:
  schedule:
    # Github Actions runs on UTC. AEST is UTC + 10 (non-Daylight Saving) / 11 (Daylight Saving)
    # https://crontab.guru
    # “At 12:00 + 10:00/11:00 = 22:00/23:00 (AEST) on every day-of-week from Sunday through Thursday.”
    - cron: "0 12 * * 0-4"
  workflow_dispatch: # For being able to manually click 'Run Workflow' button on Github Actions
jobs:
  ASX-Data-Loader:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT: Github Actions CI
      GITHUB_ACTIONS_ROOT_DIR: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Specify node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' 
      - name: Install packages
        run: |
          # Similar to npm install, except it's meant to be used in automated environments to make sure a clean install of your dependencies.
          # npm ERR! The `npm ci` command can only install with an existing package-lock.json or
          # npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
          # npm ERR! later to generate a package-lock.json file, then try again.
          npm ci
      - name: Copy all non-TS files in 'src' folder to 'dist' folder
        run: npm run prevscodedebug
      - name: Transpile to js files
        run: |
          npm run vscodedebug
      - name: Create ASX data files 
        run: |
          node ./dist/scripts/asx.js
      - name: Commit to the repo
        run: |
          git config --global user.name "${{ env.CI_COMMIT }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -a -m "Pre-Market Data Fetch" --allow-empty
          git push