name: GitHub Actions Demo
on: [push]
jobs:
  Brand new job:
    runs-on: ubuntu-latest # look for a lighter image
    env: 
      CI_COMMIT_MESSAGE: Github Actions CI Build Artifacts
      CI_COMMIT_AUTHOR: Github Actions CI
      GITHUB_ACTIONS_DEFAULT_DIR: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create a text file 
        run: |
        echo "Hello me" > ${{ github.workspace }}/dist/data/
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git pull
        git add ./dist/data/*
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
